AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Multi-Region API

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration: REGIONAL

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "GlobalPocTable"
      Events:
        PostData:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: POST
        GetData:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: GET

Outputs:
  ApiEndpoint:
    Description: "API URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
